name: AutoBuild
on:
  push:
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          context: .
          platforms: linux/amd64,linux/arm64
          tags: ${{ secrets.DOCKER_USERNAME }}/pizu:${{ github.sha }}
      - name: Deploy to acme.com/v1/cronjobs/demo/default/matt
        run: "curl -X PATCH -H \"content-type: application/json\"
          https://kblocks.io/api/resources/acme.com/v1/cronjobs/demo/default/ma\
          tt -d '{\"image\":{\"fromImage\":{\"image\":\"${{
          secrets.DOCKER_USERNAME }}/pizu:${{ github.sha }}\"}}}'"
